services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "8443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    container_name: nginx_container
    restart: unless-stopped
  
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    container_name: mariadb_container
    restart: unless-stopped
  
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        WP_DB_HOST: ${WP_DB_HOST}
        DB_NAME: ${DB_NAME}
        WP_DB_USER: ${WP_DB_USER}
        DB_PASS: ${DB_PASS}
        DOMAIN_NAME: ${DOMAIN_NAME}
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    container_name: wordpress_container
    restart: unless-stopped

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind

