from debian:bullseye

RUN apt-get update && apt-get install -y nginx

COPY ./config/nginx.conf /etc/nginx/nginx.conf

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj "/CN=prando-a.42.fr/C=ES/L=Malaga"

CMD ["nginx", "-g", "daemon off;"]